services:
  blazorshop.web:
    build:
      context: .
      dockerfile: BlazorShop.Web/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - blazorshop.api
    networks:
      - public-network

  blazorshop.api:
    build:
      context: .
      dockerfile: BlazorShop.API/Dockerfile
    ports:
      - "7150:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=blazorshop.db;Database=virtualStoreMacoratti;Username=postgres;Password=1234;
    depends_on:
      - blazorshop.db
    networks:
      - public-network
      - private-network
      
  blazorshop.db:
    image: postgres:16
    container_name: blazorshop-pgsql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: virtualStoreMacoratti
    ports:
      - "5432:5432"
    volumes:
      - blazorshop-pgdata:/var/lib/postgresql/data
    networks:
      - private-network

networks:
  public-network:
    driver: bridge
  private-network:
    driver: bridge

volumes:
  blazorshop-pgdata:
    driver: local
